export const issueData = [
	{
		issue:"以下哪一项不是希氏束起搏相对于传统的右心室起搏的优势：",
		answer:[
			{
				order:'A',
				texts:"保证双心室的同步",
				correct:false
			},
			{
				order:'B',
				texts:"保证了房室的同步",
				correct:false
			},
			{
				order:'C',
				texts:"电极体大部分位于心房端，降低了三尖瓣返流的风险",
				correct:false
			},
			{
				order:'D',
				texts:"起搏阈值较右心室起搏显著降低，电极稳定性更佳",
				correct:true
			},
		]
	},
	{
		issue:"A3的关键产品竞争优势不包括：",
		answer:[
			{
				order:'A',
				texts:"全身MRI兼容，无扫描部位限制",
				correct:false
			},
			{
				order:'B',
				texts:"任意水平体位，满足乳腺MRI的俯卧扫描要求",
				correct:false
			},
			{
				order:'C',
				texts:"配套MRI电极4074/4574/5076超15年使用经验，好机不换极",
				correct:false
			},
			{
				order:'D',
				texts:"全心AF管理，独有的rATP监测房性心律失常节律变化重启ATP治疗",
				correct:false
			},
			{
				order:'E',
				texts:"基于ICD平台的精确感知，更懂希氏束起搏的R波",
				correct:false
			},
			{
				order:'F',
				texts:"业界最好的代理商团队",
				correct:true
			},
		]
	},
	{
		issue:"根据BCS政策，专家参加美敦力自办会，飞行时间大于或等于多少小时的国际航班（不包括中转停留时间）可申请商务舱",
		answer:[
			{
				order:'A',
				texts:"6小时",
				correct:false
			},
			{
				order:'B',
				texts:"8小时",
				correct:false
			},
			{
				order:'C',
				texts:"10小时",
				correct:true
			},
			{
				order:'D',
				texts:"12小时",
				correct:false
			},
		]
	},
	{
		issue:"美敦力决定从何时起，所有美敦力业务集团和地区将停止向医生个人和其他医疗保健专业人士（HCP）参加第三方教育活动提供直接赞助。",
		answer:[
			{
				order:'A',
				texts:"2018年1月1日",
				correct:true
			},
			{
				order:'B',
				texts:"2018年2月1日",
				correct:false
			},
			{
				order:'C',
				texts:"2018年5月1日",
				correct:false
			}
		]
	},
	{
		issue:"学员必须完成全部Core1-3和Advanced1-3课程并认证后才能获得技术加薪，技术加薪周期和时间为：",
		answer:[
			{
				order:'A',
				texts:"1次/年 5月份",
				correct:false
			},
			{
				order:'B',
				texts:"1次/年 8月份",
				correct:false
			},
			{
				order:'C',
				texts:"2次/年 1月份、8月份",
				correct:true
			},
			{
				order:'D',
				texts:"2次/年 1月份、11月份",
				correct:false
			}
		]
	},
	{
		issue:"关于MIC培训，请选择描述与目前情况不符合的一项：",
		answer:[
			{
				order:'A',
				texts:"MIC可以提供右心室、右心房主动导线植入的动物模型",
				correct:false
			},
			{
				order:'B',
				texts:"对于CRT初级植入术者，提供边植入边交流（相互带教）的培训形式",
				correct:false
			},
			{
				order:'C',
				texts:"培训最重要的成功因素是导师的教授意愿高而非学员选择的合理性",
				correct:true
			},
			{
				order:'D',
				texts:"MIC培训的形式包括，专家授课，案例讨论，VCL模拟，动物实验等",
				correct:false
			}
		]
	},
	{
		issue:"以下哪项AFS市场活动是针对大中心的系列学术活动？",
		answer:[
			{
				order:'A',
				texts:"专项行冻",
				correct:false
			},
			{
				order:'B',
				texts:"行冻中国",
				correct:true
			},
			{
				order:'C',
				texts:"冰多将广 ",
				correct:false
			},
			{
				order:'D',
				texts:"专家行冻",
				correct:false
			}
		]
	},
	{
		issue:"以下关于珠峰系列培训，说法正确的有",
		answer:[
			{
				order:'A',
				texts:"珠峰大本营可以在美敦力临床培训中心硅心模型上模拟导管操作",
				correct:false
			},
			{
				order:'B',
				texts:"珠峰1号营是在全国培训中心开展的针对全新术者的培训班",
				correct:false
			},
			{
				order:'C',
				texts:"珠峰2号营主要针对已经开展手术，但尚未通过学习曲线的术者 ",
				correct:false
			},
			{
				order:'D',
				texts:"珠峰3号营旨在帮助术者提高手术成功率，提高手术效率",
				correct:false
			},
			{
				order:'E',
				texts:"以上都对",
				correct:true
			}
		]
	},
	{
		issue:"以下描述FY19 CRT项目“最美技法”错误的是：",
		answer:[
			{
				order:'A',
				texts:"“最美技法”分为网络新晋赛和区域沙龙两种主要形式",
				correct:false
			},
			{
				order:'B',
				texts:"“最美技法”主要针对CRT植入的技法开展讨论，结合美敦力CRT功能算法和左室递送工具的优势宣传",
				correct:false
			},
			{
				order:'C',
				texts:"“最美技法”主要面向CRT经验型术者和成长型术者，搭建交流平台，提高植入信心 ",
				correct:false
			},
			{
				order:'D',
				texts:"“最美技法”只推广AdaptivCRT和Smartshock",
				correct:true
			}
		]
	},
	{
		issue:"FY19 HP将持续进行产品升级，以下关于Egida和Protecta的描述中错误的是：",
		answer:[
			{
				order:'A',
				texts:"Egida在目前的产品线中会最先退市",
				correct:false
			},
			{
				order:'B',
				texts:"我们希望使用Egida来替代Maximo II",
				correct:true
			},
			{
				order:'C',
				texts:"Protecta可以等价替换Maximo II",
				correct:false
			},
			{
				order:'D',
				texts:"我们希望减少使用Egida，多使用Evera/Viva/Brava",
				correct:false
			}
		]
	},
	{
		issue:"FY19中国市场上,美敦力会有哪些C&I产品？",
		answer:[
			{
				order:'A',
				texts:"MyCareLink",
				correct:false
			},
			{
				order:'B',
				texts:"MyCareLink Smart",
				correct:false
			},
			{
				order:'C',
				texts:"CareLink Express Mobile ",
				correct:false
			},
			{
				order:'D',
				texts:"以上产品全都有",
				correct:true
			}
		]
	},
		{
		issue:"关于ICM诊疗路径，正确的描述是：",
		answer:[
			{
				order:'A',
				texts:"需要心内科，神经科，急诊科等多个科室共同参与",
				correct:false
			},
			{
				order:'B',
				texts:"Reveal LINQ作为ICM的最佳选择，得到广泛认可",
				correct:false
			},
			{
				order:'C',
				texts:"2018ESC指南新增晕厥诊疗单元（Syncope unit）内容 ",
				correct:false
			},
			{
				order:'D',
				texts:"ICM临床路径大赛有助于ICM诊疗路径的建立",
				correct:false
			},
			{
				order:'E',
				texts:"以上都对",
				correct:true
			}
		]
	}
]

